services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "MODRINTH"
      MODS_FILE: "/extras/mods.txt"
      MODRINTH_MODPACK: "landscapes-reimagined-genesis"
      MODRINTH_EXCLUDE_FILES: |
        fancymenu
        drippyloadingscreen
      MEMORY: "6G"
    healthcheck:
      test: mc-health
      start_period: 5m
      interval: 5s
      retries: 20
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      - ./mods.txt:/extras/mods.txt:ro